### PR TITLE
Add Social icons to the footer with hover effects [Fixes #22]

### LINKED ISSUE #22: [FEATURE] <Adding Social icons to the footer with hover effects>
### Detailed description

Adding Social icons to the footer with hover effects

Assign this issue to me

### Context

Adding Social icons to the footer with hover effects

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Kritika30032002**
## Fixes Issue
Fixes #22 

## Changes proposed
Add Social icons to the footer with hover effects

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
hey @Kritika30032002 
We are using react-icons so you can use these icon: https://react-icons.github.io/react-icons/search

And here are the social links you can use: https://linktr.ee/cryptoverseWeb3

If you need any help or have any doubts, you can ask here.

thank you

**Comment by Kritika30032002** [comment]
okay

**Comment by kabir0x23** [comment]
> okay

You don't have to close the pr
You can simply push the code on the same branch, and the code will automatically be reflected here.

**Comment by Kritika30032002** [comment]
> > okay
> 
> You don't have to close the pr You can simply push the code on the same branch, and the code will automatically be reflected here.

Okay

**Pull request closed without merging**
