### PR TITLE
Add Blog Page 

### LINKED ISSUE #3: [FEATURE] Blogs page
### Detailed description

Add a Blog section to the site
Can be made using React
- Add dummy data after completing this page, we will add backend later on.
### Context

Blogs plays important role in learning

### Possible implementation

Example: 👇
- Add blog nav-item under navbar
- You can make this type UI under the blog section.
- image
- website: https://www.cryptoverseweb3.com/

### Additional information

If you need any help or have questions and doubts, please ask below: 👇 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Manthan-Kuber**
---
## Fixes Issue
closes #3 

## Changes proposed
Added Blog Card Component and blogs page with dummy data
Page is responsive and has a grid layout
Have added props for Card such that when real data from backend is fetched, you can simply pass on the data to the component as props

## Screenshots
image

## Code of Conduct
- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

---

### CODE REVIEW

**Review by kabir0x23 — COMMENTED** [review]
Nice you did a an amaing work
___ 

can you do one thing?
- remove all the other blogs keep 1-2 blogs right now.
- and you can use temporay images and headings from this urls
- https://www.coinbase.com/learn

If you need any help let us know.

**Comment by Manthan-Kuber** [comment]
> Nice you did a an amaing work
> 
> can you do one thing?
> 
>     * remove all the other blogs keep 1-2 blogs right now.
> 
>     * and you can use temporay images and headings from this urls
> 
>     * https://www.coinbase.com/learn
> 
> 
> If you need any help let us know.

Thanks. So should I close my pr and raise another one after commit ?

**Comment by kabir0x23** [comment]
> > Nice you did a an amaing work
> > can you do one thing?
> > ```
> > * remove all the other blogs keep 1-2 blogs right now.
> > 
> > * and you can use temporay images and headings from this urls
> > 
> > * https://www.coinbase.com/learn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you need any help let us know.
> 
> Thanks. So should I close my pr and raise another one after commit ?

there was no need for closing this PR.
you just have to change your code and pull 
changes will be automatically reflated in your PR

**Comment by Manthan-Kuber** [comment]
@kabir0x23  oops. Now should I delete my new one and open this back up or what xD

**Comment by kabir0x23** [comment]
> @kabir0x23 oops. Now should I delete my new one and open this back up or what xD

It's okay now, New PR is also fine.

**Pull request closed without merging**
