### PR TITLE
Feature/infinite scroll

### LINKED ISSUE #2: [FEATURE] Add Infinite scroll
### Detailed description

I suggest to add infinite scroll in news section so that the news that are not able to fit in the screen able to visible by scrolling down. 

### Context

With this feature, the news count will be increased, there is only 9-12 news on screen but with infinite scroll, user can view news as much as they want.

The infinite scroll also solves the problem of pagination. 

- Pre-loading News will slow the website for the users, so we can load the news while the user is scrolling and news will start loading so that pre-loading the news  

### Possible implementation

image

Example: loading icon while fetching the news
### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Manthan-Kuber**
## Fixes Issue
closes #2 

## Changes proposed
Added infinite scroll
Infinite scroll is dependent mainly on 3 params, a boolean which tells the component if more data is to be fetched, a function which fetches more data and lastly length of the  current data
Have also fixed layout issue happening due to antd col component

## Screenshots
image

## Note to reviewers
Check layout and add loader component and end message as you please
For now there's a simple paragraph tag that says loading
The extra changes to other components might be present because I solved the blog page issue as well. Nevertheless changes should merge
Please use typescript next time. Working with rtk query becomes increasingly complex when you are passing callback functions and / or making manual update to cached query data. Have to console log the data every time to check if I am accessing the right property

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

### CODE REVIEW

**Comment by Manthan-Kuber** [comment]
@kabir0x23 Hi. Can you please check and merge both of my pull requests

**Comment by kabir0x23** [comment]
> @kabir0x23 Hi. Can you please check and merge both of my pull requests

Hey @Manthan-Kuber 
Yes we are checking it now, will merge it by today 

Thanks

**Review by kabir0x23 — COMMENTED** [review]
I have a suggestions. and an issue.

Whenever we work on new issues,.
Always create new branches

---

Now we have 2 PRs 
1. containing blogs
2. infinite scroll + blogs

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks for contributing to this project.

**Pull request merged**
