### PR TITLE
#12 [FEATURE] Improve background design of NEWS page 

### PR DESCRIPTION
**Pull request by Hrx4**
## Code of Conduct
- [ x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [ x] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. 
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). 
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by Hrx4** [comment]
WhatsApp Image 2022-10-16 at 6 28 19 PM

**Comment by Hrx4** [comment]
previous back gorund ->
WhatsApp Image 2022-10-16 at 6 28 19 PM
new background ->
WhatsApp Image 2022-10-16 at 6 28 46 PM

**Comment by kabir0x23** [comment]
you can simply edit the pr and will able to add screenshots easily, 

image

**Comment by kabir0x23** [comment]
> previous back gorund -> WhatsApp Image 2022-10-16 at 6 28 19 PM new background -> WhatsApp Image 2022-10-16 at 6 28 46 PM

awesome looking nice

**Comment by kabir0x23** [comment]
don;t close

**Comment by kabir0x23** [comment]
> don;t close

you don;'t have to close the PRs
and there is no need to close the PR

**Comment by Hrx4** [comment]
Actually , i am new to open source and github , i will keep this in mind , thanks for the informaton.🤗

**Comment by kabir0x23** [comment]
> Actually , i am new to open source and github , i will keep this in mind , thanks for the informaton.🤗

Awesome 🔥

**Pull request closed without merging**
