### PR TITLE
#12 [FEATURE] Improve background design of NEWS page

### LINKED ISSUE #11: [FEATURE] Improve background design of cryptocurrencies page
### Detailed description

 Improve background design of cryptocurrencies page

same design as the home page or something good you can try

### Context

image

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #12: [FEATURE] Improve background design of NEWS page
### Detailed description

Improve background design of NEWS page

image

### Context

https://www.cryptoverseweb3.com/news

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Hrx4**
closes #12 
closes #15 
closes #11 

## Code of Conduct
- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. 
Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). 
Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
> ## Fixes Issue
> ## Changes proposed
> ## Screenshots
> ## Note to reviewers
> ## Code of Conduct
> 
>     * [ ]  By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/CryptoverseWeb3/Support/blob/main/CODE_OF_CONDUCT.md) 🖖
> 
> 
> ## Check List (Check all the applicable boxes)
> 
>     * [ ]  My code follows the code style of this project.
> 
>     * [ ]  My change requires changes to the documentation.
> 
>     * [ ]  I have updated the documentation accordingly.
> 
>     * [ ]  All new and existing tests passed.
> 
>     * [ ]  This PR does not contain plagiarized content.
> 
>     * [ ]  The title of my pull request is a short description of the requested changes.
> 
> 
> You can also join our [Discord](https://discord.gg/WhDry9FWE7) community. Feel free to check out other cool repositories of the [Cryptoverse Web3](https://github.com/CryptoverseWeb3). Join the Cryptoverse Web3 GitHub Organisation by raising an [issue](https://github.com/CryptoverseWeb3/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

Hey, can you will the details, it will be easy for the maintainers

**Comment by Hrx4** [comment]
Hey @kabir0x23  i think i done the checkboxes , please check it , if any issue please tell me.

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 i think i done the checkboxes , please check it , if any issue please tell me.

screenshots..
please if possible add those too, it will be every easy for maintainers to review the PR

**Comment by kabir0x23** [comment]
what happend?

**Comment by Hrx4** [comment]
Hey @kabir0x23  please merge this issue, I accidently closed this PR.

**Comment by Hrx4** [comment]
previous background ->
WhatsApp Image 2022-10-16 at 6 28 19 PM
New background ->
WhatsApp Image 2022-10-16 at 6 28 46 PM

Here the screenshots.

**Review by kabir0x23 — APPROVED** [review]
Awesome 

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

**Pull request merged**
